[2024-10-31T02:18:39.548+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-31T02:18:39.562+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_scrapping_dag.task scheduled__2024-10-31T01:00:00+00:00 [queued]>
[2024-10-31T02:18:39.571+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_scrapping_dag.task scheduled__2024-10-31T01:00:00+00:00 [queued]>
[2024-10-31T02:18:39.571+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-31T02:18:39.581+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): task> on 2024-10-31 01:00:00+00:00
[2024-10-31T02:18:39.588+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1400) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-31T02:18:39.591+0000] {standard_task_runner.py:72} INFO - Started process 1401 to run task
[2024-10-31T02:18:39.592+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_scrapping_dag', 'task', 'scheduled__2024-10-31T01:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_with_python.py', '--cfg-path', '/tmp/tmp9du6xev6']
[2024-10-31T02:18:39.596+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask task
[2024-10-31T02:18:39.645+0000] {task_command.py:467} INFO - Running <TaskInstance: web_scrapping_dag.task scheduled__2024-10-31T01:00:00+00:00 [running]> on host 0c345cfeaacd
[2024-10-31T02:18:39.722+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_scrapping_dag' AIRFLOW_CTX_TASK_ID='task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-31T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-31T01:00:00+00:00'
[2024-10-31T02:18:39.724+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-31T02:18:40.636+0000] {logging_mixin.py:190} INFO - data/30.10.2024.csv ------
[2024-10-31T02:18:40.777+0000] {logging_mixin.py:190} INFO - Saved article: Hindistondagi yirik yangiliklar agentligi Wikipedia’ni sudga berdi
[2024-10-31T02:18:40.915+0000] {logging_mixin.py:190} INFO - Saved article: Reddit ijtimoiy tarmog‘i 20 yil ichida birinchi marta foyda ko‘rdi
[2024-10-31T02:18:41.052+0000] {logging_mixin.py:190} INFO - Saved article: AQSh Rossiya «do‘stlariga» qarshi sanksiyalar kiritdi
[2024-10-31T02:18:41.349+0000] {logging_mixin.py:190} INFO - Saved article: Qozog‘istonda davlat xizmatchilariga mukofot pullarini ajratish taqiqlandi
[2024-10-31T02:18:41.512+0000] {logging_mixin.py:190} INFO - Saved article: Erdo‘g‘an kurdlarni «Turkiya asrini» birgalikda qurishga chaqirdi
[2024-10-31T02:18:41.682+0000] {logging_mixin.py:190} INFO - Saved article: Trampning tarafdorlari Bayden ularni «chiqindi» deb ataganini aytishmoqda
[2024-10-31T02:18:41.864+0000] {logging_mixin.py:190} INFO - Saved article: «Hizbulloh»ning yangi rahbari Nasrullohning yo‘lini davom ettirishga va’da berdi
[2024-10-31T02:18:42.088+0000] {logging_mixin.py:190} INFO - Saved article: Turkiyada 8 ming yilga qamalgan Adnan Oktarning mulki musodara qilindi
[2024-10-31T02:18:42.209+0000] {logging_mixin.py:190} INFO - Saved article: Dekabr oyi oxirida MDH norasmiy sammiti bo‘lib o‘tadi
[2024-10-31T02:18:42.347+0000] {logging_mixin.py:190} INFO - Saved article: Yevropada sun’iy intellekt sabab millionlab ish o‘rinlari xavf ostida qolmoqda
[2024-10-31T02:18:42.458+0000] {logging_mixin.py:190} INFO - Saved article: Rossiya Davlat xizmatlari Google servislarini o‘chirishga tayyorgarlik boshladi
[2024-10-31T02:18:42.587+0000] {logging_mixin.py:190} INFO - Saved article: 30 oktyabr yangiliklari: O‘zbekistonda ro‘y bergan muhim voqea va hodisalar
[2024-10-31T02:18:42.793+0000] {logging_mixin.py:190} INFO - Saved article: Britaniyadagi atom suvosti kemalari ishlab chiqariladigan korxonada yong‘in yuz berdi
[2024-10-31T02:18:43.474+0000] {logging_mixin.py:190} INFO - Saved article: Toshkentga to‘rtta kirish darvozasi quriladi
[2024-10-31T02:18:43.592+0000] {logging_mixin.py:190} INFO - Saved article: Farg‘onada jamoat transporti yo‘l haqi oshirildi
[2024-10-31T02:18:43.744+0000] {logging_mixin.py:190} INFO - Saved article: Gurjistonda saylovlar bo‘yicha tergov boshlandi. Mamlakat prezidenti so‘roqqa chaqirildi
[2024-10-31T02:18:44.332+0000] {logging_mixin.py:190} INFO - Saved article: Chery 2024 Xalqaro foydalanuvchilar sammiti yakunlandi
[2024-10-31T02:18:44.578+0000] {logging_mixin.py:190} INFO - Saved article: Maktab darsliklari ijarasi uchun to‘lov tiklanishi mumkin
[2024-10-31T02:18:44.903+0000] {logging_mixin.py:190} INFO - Saved article: Saida Mirziyoyeva Fashion Trust Arabia taqdirlash marosimida ishtirok etdi
[2024-10-31T02:18:45.028+0000] {logging_mixin.py:190} INFO - Saved article: Maktabgacha va maktab ta’limi vaziriga yangi birinchi o‘rinbosar tayinlandi
[2024-10-31T02:18:45.186+0000] {logging_mixin.py:190} INFO - Saved article: Sovuq tushdi, ammo uylarga issiqlik berilmayapti. Nega?
[2024-10-31T02:18:45.377+0000] {logging_mixin.py:190} INFO - Saved article: 2025 yil uchun davlat budjeti: qaysi tashkilotga qancha pul ajratiladi?
[2024-10-31T02:18:45.570+0000] {logging_mixin.py:190} INFO - Saved article: Surxondaryoda isitish mavsumi 1 noyabrdan boshlanadi
[2024-10-31T02:18:45.770+0000] {logging_mixin.py:190} INFO - Saved article: BMW, Mercedes, Porsche va boshqa nemis kompaniyalarida umummilliy ish tashlash boshlandi
[2024-10-31T02:18:45.936+0000] {logging_mixin.py:190} INFO - Saved article: Alimentdan qochib yurgan otani “ilintirgan” xodim – MIB operatsiyasi tafsilotlari
[2024-10-31T02:18:46.065+0000] {logging_mixin.py:190} INFO - Saved article: Dunyoda silga chalinish holatlari oshdi – JSST
[2024-10-31T02:18:46.218+0000] {logging_mixin.py:190} INFO - Saved article: «Dahshatli voqea». AQSh yana o‘nlab kishi o‘ldirilishi ortidan G‘azodagi urushni yakunlashga chaqirdi
[2024-10-31T02:18:47.263+0000] {logging_mixin.py:190} INFO - Saved article: Atlas Mebel Beruniy: 1 noyabr kuni zamonaviy mebel bozori o‘z eshiklarini ochadi
[2024-10-31T02:18:47.389+0000] {logging_mixin.py:190} INFO - Saved article: Farg‘onada saylov qonunchiligini buzgan uchastka saylov komissiyasi a’zosi ma’muriy jazoga tortildi
[2024-10-31T02:18:47.520+0000] {logging_mixin.py:190} INFO - Saved article: Ispaniyada suv toshqini. 50 dan ortiq kishi halok bo‘lgan
[2024-10-31T02:18:47.678+0000] {logging_mixin.py:190} INFO - Saved article: Yangi uzilgan meva-sabzavotlarning “umrini uzaytirish” usuli ma’lum qilindi
[2024-10-31T02:18:47.793+0000] {logging_mixin.py:190} INFO - Saved article: Zelenskiy Shimoliy kengashni Ukrainani NATOga taklif qilishga chaqirdi
[2024-10-31T02:18:47.925+0000] {logging_mixin.py:190} INFO - Saved article: Enso Mayorka - ovchidan tabiat himoyachisiga aylangan sportchi haqida hikoya
[2024-10-31T02:18:48.319+0000] {logging_mixin.py:190} INFO - Saved article: Ma’lumotlar “kaft ustida” bo‘lsa, to‘g‘ri qaror chiqarish ehtimoli ortadi – Toshkentda ma’lumotlarni boshqarish mavzusida konferensiya bo‘lib o‘tdi
[2024-10-31T02:18:48.443+0000] {logging_mixin.py:190} INFO - Saved article: Rossiyada mahsulotlar narxi 2025 yilda 20 foizga oshishi mumkin
[2024-10-31T02:18:48.625+0000] {logging_mixin.py:190} INFO - Saved article: Vinisiusning fanatlari nafratini Rodrining «adash»lariga sochishdi
[2024-10-31T02:18:48.844+0000] {logging_mixin.py:190} INFO - Saved article: Yaponiyadagi qishloqda keksalar yolg‘izlikni yengish uchun ko‘chalarga qo‘g‘irchoqlar o‘rnatyapti
[2024-10-31T02:18:49.013+0000] {logging_mixin.py:190} INFO - Saved article: Olimlar saratonni sun’iy intellekt yordamida davolashning yangi usulini kashf etdi
[2024-10-31T02:34:59.667+0000] {job.py:229} INFO - Heartbeat recovered after 954.76 seconds
[2024-10-31T02:36:44.667+0000] {job.py:229} INFO - Heartbeat recovered after 79.74 seconds
[2024-10-31T03:09:31.509+0000] {job.py:229} INFO - Heartbeat recovered after 1940.85 seconds
[2024-10-31T03:19:09.851+0000] {job.py:229} INFO - Heartbeat recovered after 553.13 seconds
[2024-10-31T03:19:32.530+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_dag_with_python.py", line 59, in start_scrapping
    item_page = requests.get(URL + itam_page_link)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2024-10-31T03:19:32.596+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=web_scrapping_dag, task_id=task, run_id=scheduled__2024-10-31T01:00:00+00:00, execution_date=20241031T010000, start_date=20241031T021839, end_date=20241031T031932
[2024-10-31T03:19:32.614+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-31T03:19:32.616+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task task (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')); 1401)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_dag_with_python.py", line 59, in start_scrapping
    item_page = requests.get(URL + itam_page_link)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2024-10-31T03:19:32.675+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-31T03:19:32.704+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-31T03:19:32.705+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
