[2024-10-31T03:09:28.124+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-31T03:09:28.133+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_scrapping_dag.task scheduled__2024-10-31T02:00:00+00:00 [queued]>
[2024-10-31T03:09:28.138+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_scrapping_dag.task scheduled__2024-10-31T02:00:00+00:00 [queued]>
[2024-10-31T03:09:28.138+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-31T03:09:28.144+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): task> on 2024-10-31 02:00:00+00:00
[2024-10-31T03:09:28.148+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1417) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-31T03:09:28.149+0000] {standard_task_runner.py:72} INFO - Started process 1418 to run task
[2024-10-31T03:09:28.150+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_scrapping_dag', 'task', 'scheduled__2024-10-31T02:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_with_python.py', '--cfg-path', '/tmp/tmpxuie90t7']
[2024-10-31T03:09:28.153+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask task
[2024-10-31T03:09:28.197+0000] {task_command.py:467} INFO - Running <TaskInstance: web_scrapping_dag.task scheduled__2024-10-31T02:00:00+00:00 [running]> on host 0c345cfeaacd
[2024-10-31T03:09:28.251+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_scrapping_dag' AIRFLOW_CTX_TASK_ID='task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-31T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-31T02:00:00+00:00'
[2024-10-31T03:09:28.253+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-31T03:09:28.778+0000] {logging_mixin.py:190} INFO - data/30.10.2024.csv ------
[2024-10-31T03:09:28.940+0000] {logging_mixin.py:190} INFO - Saved article: Hindistondagi yirik yangiliklar agentligi Wikipedia’ni sudga berdi
[2024-10-31T03:09:29.056+0000] {logging_mixin.py:190} INFO - Saved article: Reddit ijtimoiy tarmog‘i 20 yil ichida birinchi marta foyda ko‘rdi
[2024-10-31T03:09:29.173+0000] {logging_mixin.py:190} INFO - Saved article: AQSh Rossiya «do‘stlariga» qarshi sanksiyalar kiritdi
[2024-10-31T03:09:29.321+0000] {logging_mixin.py:190} INFO - Saved article: Qozog‘istonda davlat xizmatchilariga mukofot pullarini ajratish taqiqlandi
[2024-10-31T03:09:29.491+0000] {logging_mixin.py:190} INFO - Saved article: Erdo‘g‘an kurdlarni «Turkiya asrini» birgalikda qurishga chaqirdi
[2024-10-31T03:09:29.690+0000] {logging_mixin.py:190} INFO - Saved article: Trampning tarafdorlari Bayden ularni «chiqindi» deb ataganini aytishmoqda
[2024-10-31T03:09:29.825+0000] {logging_mixin.py:190} INFO - Saved article: «Hizbulloh»ning yangi rahbari Nasrullohning yo‘lini davom ettirishga va’da berdi
[2024-10-31T03:09:29.955+0000] {logging_mixin.py:190} INFO - Saved article: Turkiyada 8 ming yilga qamalgan Adnan Oktarning mulki musodara qilindi
[2024-10-31T03:09:30.119+0000] {logging_mixin.py:190} INFO - Saved article: Dekabr oyi oxirida MDH norasmiy sammiti bo‘lib o‘tadi
[2024-10-31T03:09:30.301+0000] {logging_mixin.py:190} INFO - Saved article: Yevropada sun’iy intellekt sabab millionlab ish o‘rinlari xavf ostida qolmoqda
[2024-10-31T03:09:30.427+0000] {logging_mixin.py:190} INFO - Saved article: Rossiya Davlat xizmatlari Google servislarini o‘chirishga tayyorgarlik boshladi
[2024-10-31T03:09:30.567+0000] {logging_mixin.py:190} INFO - Saved article: 30 oktyabr yangiliklari: O‘zbekistonda ro‘y bergan muhim voqea va hodisalar
[2024-10-31T03:09:30.759+0000] {logging_mixin.py:190} INFO - Saved article: Britaniyadagi atom suvosti kemalari ishlab chiqariladigan korxonada yong‘in yuz berdi
[2024-10-31T03:09:31.126+0000] {logging_mixin.py:190} INFO - Saved article: Toshkentga to‘rtta kirish darvozasi quriladi
[2024-10-31T03:09:31.325+0000] {logging_mixin.py:190} INFO - Saved article: Farg‘onada jamoat transporti yo‘l haqi oshirildi
[2024-10-31T03:09:31.468+0000] {logging_mixin.py:190} INFO - Saved article: Gurjistonda saylovlar bo‘yicha tergov boshlandi. Mamlakat prezidenti so‘roqqa chaqirildi
[2024-10-31T03:09:31.729+0000] {logging_mixin.py:190} INFO - Saved article: Chery 2024 Xalqaro foydalanuvchilar sammiti yakunlandi
[2024-10-31T03:09:31.853+0000] {logging_mixin.py:190} INFO - Saved article: Maktab darsliklari ijarasi uchun to‘lov tiklanishi mumkin
[2024-10-31T03:09:31.969+0000] {logging_mixin.py:190} INFO - Saved article: Saida Mirziyoyeva Fashion Trust Arabia taqdirlash marosimida ishtirok etdi
[2024-10-31T03:09:33.267+0000] {logging_mixin.py:190} INFO - Saved article: Maktabgacha va maktab ta’limi vaziriga yangi birinchi o‘rinbosar tayinlandi
[2024-10-31T03:09:33.456+0000] {logging_mixin.py:190} INFO - Saved article: Sovuq tushdi, ammo uylarga issiqlik berilmayapti. Nega?
[2024-10-31T03:09:35.952+0000] {logging_mixin.py:190} INFO - Saved article: 2025 yil uchun davlat budjeti: qaysi tashkilotga qancha pul ajratiladi?
[2024-10-31T03:09:36.141+0000] {logging_mixin.py:190} INFO - Saved article: Surxondaryoda isitish mavsumi 1 noyabrdan boshlanadi
[2024-10-31T03:09:36.274+0000] {logging_mixin.py:190} INFO - Saved article: BMW, Mercedes, Porsche va boshqa nemis kompaniyalarida umummilliy ish tashlash boshlandi
[2024-10-31T03:09:36.416+0000] {logging_mixin.py:190} INFO - Saved article: Alimentdan qochib yurgan otani “ilintirgan” xodim – MIB operatsiyasi tafsilotlari
[2024-10-31T03:09:36.612+0000] {logging_mixin.py:190} INFO - Saved article: Dunyoda silga chalinish holatlari oshdi – JSST
[2024-10-31T03:09:36.814+0000] {logging_mixin.py:190} INFO - Saved article: «Dahshatli voqea». AQSh yana o‘nlab kishi o‘ldirilishi ortidan G‘azodagi urushni yakunlashga chaqirdi
[2024-10-31T03:09:37.812+0000] {logging_mixin.py:190} INFO - Saved article: Atlas Mebel Beruniy: 1 noyabr kuni zamonaviy mebel bozori o‘z eshiklarini ochadi
[2024-10-31T03:09:38.012+0000] {logging_mixin.py:190} INFO - Saved article: Farg‘onada saylov qonunchiligini buzgan uchastka saylov komissiyasi a’zosi ma’muriy jazoga tortildi
[2024-10-31T03:09:38.162+0000] {logging_mixin.py:190} INFO - Saved article: Ispaniyada suv toshqini. 50 dan ortiq kishi halok bo‘lgan
[2024-10-31T03:09:38.287+0000] {logging_mixin.py:190} INFO - Saved article: Yangi uzilgan meva-sabzavotlarning “umrini uzaytirish” usuli ma’lum qilindi
[2024-10-31T03:09:38.528+0000] {logging_mixin.py:190} INFO - Saved article: Zelenskiy Shimoliy kengashni Ukrainani NATOga taklif qilishga chaqirdi
[2024-10-31T03:09:38.803+0000] {logging_mixin.py:190} INFO - Saved article: Enso Mayorka - ovchidan tabiat himoyachisiga aylangan sportchi haqida hikoya
[2024-10-31T03:09:38.972+0000] {logging_mixin.py:190} INFO - Saved article: Ma’lumotlar “kaft ustida” bo‘lsa, to‘g‘ri qaror chiqarish ehtimoli ortadi – Toshkentda ma’lumotlarni boshqarish mavzusida konferensiya bo‘lib o‘tdi
[2024-10-31T03:09:39.111+0000] {logging_mixin.py:190} INFO - Saved article: Rossiyada mahsulotlar narxi 2025 yilda 20 foizga oshishi mumkin
[2024-10-31T03:09:39.259+0000] {logging_mixin.py:190} INFO - Saved article: Vinisiusning fanatlari nafratini Rodrining «adash»lariga sochishdi
[2024-10-31T03:09:39.499+0000] {logging_mixin.py:190} INFO - Saved article: Yaponiyadagi qishloqda keksalar yolg‘izlikni yengish uchun ko‘chalarga qo‘g‘irchoqlar o‘rnatyapti
[2024-10-31T03:09:39.690+0000] {logging_mixin.py:190} INFO - Saved article: Olimlar saratonni sun’iy intellekt yordamida davolashning yangi usulini kashf etdi
[2024-10-31T03:09:39.846+0000] {logging_mixin.py:190} INFO - Saved article: UQK generali Marchenko: Donbassdagi front «parchalandi»
[2024-10-31T03:09:39.985+0000] {logging_mixin.py:190} INFO - Saved article: Oliy rada Ukrainadagi harbiy holatni uzaytirdi
[2024-10-31T03:09:41.365+0000] {logging_mixin.py:190} INFO - Saved article: Toshkentda yuz-jag‘ jarrohligiga ixtisoslashgan yangi SAIF PROFACE klinikasi ish boshladi
[2024-10-31T03:09:41.537+0000] {logging_mixin.py:190} INFO - Saved article: Kiyev va Seul KXDRga qarshi turish uchun aloqalarni faollashtirmoqda
[2024-10-31T03:09:41.659+0000] {logging_mixin.py:190} INFO - Saved article: Italiyada farrosh ayol 50 ming yevrolik pul va taqinchoqlar solingan eski to‘shakni chiqindiga tashlab yubordi
[2024-10-31T03:09:41.812+0000] {logging_mixin.py:190} INFO - Saved article: Toyota avtomobillarini ishlab chiqarish hajmi ketma-ket sakkizinchi oy pasaydi, sotuvlar ham qisqardi
[2024-10-31T03:09:42.072+0000] {logging_mixin.py:190} INFO - Saved article: 2025 yilda qaysi yo‘nalishga qancha subsidiya ajratiladi?
[2024-10-31T03:09:42.317+0000] {logging_mixin.py:190} INFO - Saved article: Berlin va YeI GFR fuqarosining Eronda qatl etilishiga javob berilishini va’da qildi
[2024-10-31T03:09:42.468+0000] {logging_mixin.py:190} INFO - Saved article: Borrel Gurjiston saylovlari bo‘yicha «shaffof tekshiruv»ni talab qildi
[2024-10-31T03:19:06.614+0000] {job.py:229} INFO - Heartbeat recovered after 553.15 seconds
[2024-10-31T03:19:08.958+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_dag_with_python.py", line 59, in start_scrapping
    item_page = requests.get(URL + itam_page_link)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2024-10-31T03:19:08.989+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=web_scrapping_dag, task_id=task, run_id=scheduled__2024-10-31T02:00:00+00:00, execution_date=20241031T020000, start_date=20241031T030928, end_date=20241031T031908
[2024-10-31T03:19:09.004+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-31T03:19:09.006+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task task (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')); 1418)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/first_dag_with_python.py", line 59, in start_scrapping
    item_page = requests.get(URL + itam_page_link)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2024-10-31T03:19:09.058+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-31T03:19:09.076+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-31T03:19:09.077+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
